"""Jest (JavaScript) templates and QA standards for script generation."""

from __future__ import annotations

import json
from textwrap import dedent

from app.models.schemas import APIType


# ---------------------------------------------------------------------------
# Setup files
# ---------------------------------------------------------------------------

def build_jest_config() -> str:
    return dedent(
        """\
        /** @type {import('jest').Config} */
        module.exports = {
          testEnvironment: 'node',
          testTimeout: 30000,
          verbose: true,
        };
        """
    )


def build_package_json(ticket_id: str) -> str:
    slug = ticket_id.lower().replace("-", "_")
    pkg = {
        "name": f"qa-tests-{ticket_id.lower()}",
        "version": "1.0.0",
        "description": f"Generated QA automation tests for {ticket_id}",
        "scripts": {
            "test": "jest",
            "test:verbose": "jest --verbose",
        },
        "devDependencies": {
            "jest": "^29.0.0",
            "axios": "^1.7.0",
        },
    }
    return json.dumps(pkg, indent=2)


def build_jest_setup(ticket_id: str, base_url: str, api_type: APIType) -> str:
    """Return a setup.js file with shared helpers per API type."""
    if api_type == APIType.GRAPHQL:
        return _jest_setup_graphql(ticket_id, base_url)
    if api_type == APIType.WEBSOCKET:
        return _jest_setup_websocket(ticket_id, base_url)
    return _jest_setup_rest(ticket_id, base_url)


def _jest_setup_rest(ticket_id: str, base_url: str) -> str:
    return dedent(
        f"""\
        /**
         * Shared setup for {ticket_id} REST automation tests.
         * Generated by QA Script Generator.
         */
        const axios = require('axios');

        const BASE_URL = process.env.API_BASE_URL || {json.dumps(base_url)};
        const API_KEY  = process.env.API_KEY || '';

        function createClient() {{
          return axios.create({{
            baseURL: BASE_URL,
            timeout: 30000,
            headers: {{
              'Content-Type': 'application/json',
              ...(API_KEY ? {{ Authorization: `Bearer ${{API_KEY}}` }} : {{}}),
            }},
            validateStatus: () => true,   // never throw on non-2xx; assert manually
          }});
        }}

        module.exports = {{ BASE_URL, API_KEY, createClient }};
        """
    )


def _jest_setup_graphql(ticket_id: str, graphql_url: str) -> str:
    return dedent(
        f"""\
        /**
         * Shared setup for {ticket_id} GraphQL tests.
         * Generated by QA Script Generator.
         */
        const axios = require('axios');

        const GRAPHQL_URL = process.env.GRAPHQL_URL || {json.dumps(graphql_url)};
        const API_KEY     = process.env.API_KEY || '';

        function createGqlClient() {{
          return axios.create({{
            baseURL: GRAPHQL_URL,
            timeout: 30000,
            headers: {{
              'Content-Type': 'application/json',
              ...(API_KEY ? {{ Authorization: `Bearer ${{API_KEY}}` }} : {{}}),
            }},
            validateStatus: () => true,
          }});
        }}

        async function gql(client, query, variables = null) {{
          const body = {{ query }};
          if (variables) body.variables = variables;
          return client.post('', body);
        }}

        module.exports = {{ GRAPHQL_URL, API_KEY, createGqlClient, gql }};
        """
    )


def _jest_setup_websocket(ticket_id: str, ws_url: str) -> str:
    ws = ws_url.replace("https://", "wss://").replace("http://", "ws://")
    return dedent(
        f"""\
        /**
         * Shared setup for {ticket_id} WebSocket tests.
         * Generated by QA Script Generator.
         * Requires: npm install ws
         */
        const WebSocket = require('ws');

        const WS_URL = process.env.WS_URL || {json.dumps(ws)};

        function connect(url = WS_URL, timeout = 5000) {{
          return new Promise((resolve, reject) => {{
            const ws = new WebSocket(url);
            const timer = setTimeout(() => {{ ws.close(); reject(new Error('WS connect timeout')); }}, timeout);
            ws.on('open', () => {{ clearTimeout(timer); resolve(ws); }});
            ws.on('error', (err) => {{ clearTimeout(timer); reject(err); }});
          }});
        }}

        function sendAndReceive(ws, payload, timeout = 5000) {{
          return new Promise((resolve, reject) => {{
            const timer = setTimeout(() => reject(new Error('WS recv timeout')), timeout);
            ws.once('message', (data) => {{ clearTimeout(timer); resolve(JSON.parse(data.toString())); }});
            ws.send(JSON.stringify(payload));
          }});
        }}

        module.exports = {{ WS_URL, connect, sendAndReceive }};
        """
    )


# ---------------------------------------------------------------------------
# QA standards prompts
# ---------------------------------------------------------------------------

_REST_JEST_STANDARDS = """Internal QA automation standards for Jest + REST APIs (MUST follow exactly):
- Generate a single valid JavaScript test file (.test.js).
- Import setup helpers: const { BASE_URL, createClient } = require('./setup');
- Create the axios client once at the top of the describe block: const client = createClient();
- Group tests with describe('<ticket_id>: <summary>', () => { ... }).
- One test() per scenario; name: test('<type>: <scenario name>', async () => { ... }).
- Structure: // Arrange / // Act / // Assert comments in each test.
- Assertions: expect(response.status).toBe(200); expect(response.data).toBeDefined(); etc.
- For negative tests: expect([400, 401, 403, 404, 422]).toContain(response.status);
- Build full paths: const url = `/your/endpoint`; (axios uses baseURL from client)
- Do NOT import or redefine setup helpers.
- Do NOT use beforeAll/afterAll for client creation (use top-level in describe).
- Output ONLY valid JavaScript source for a single .test.js file. No markdown fences, no explanation."""

_GRAPHQL_JEST_STANDARDS = """Internal QA automation standards for Jest + GraphQL (MUST follow exactly):
- Generate a single valid JavaScript .test.js file.
- Import: const { GRAPHQL_URL, createGqlClient, gql } = require('./setup');
- Create client once: const client = createGqlClient();
- Group with describe('<ticket_id>: <summary>', () => { ... }).
- One test() per scenario.
- Structure: // Arrange / // Act / // Assert comments.
- Call: const response = await gql(client, query, variables);
- GraphQL always returns HTTP 200; check response.data.data for success, response.data.errors for errors.
- Positive: expect(response.status).toBe(200); expect(response.data.errors).toBeUndefined();
- Negative: expect(response.data.errors).toBeDefined(); expect(response.data.errors.length).toBeGreaterThan(0);
- Write queries as template literals: const query = `query { ... }`;
- Output ONLY valid JavaScript. No markdown fences, no explanation."""

_WEBSOCKET_JEST_STANDARDS = """Internal QA automation standards for Jest + WebSocket (MUST follow exactly):
- Generate a single valid JavaScript .test.js file.
- Import: const { WS_URL, connect, sendAndReceive } = require('./setup');
- Add at top: jest.setTimeout(15000); for WS tests.
- Group with describe('<ticket_id>: <summary>', () => { ... }).
- Each test closes the WebSocket in an afterEach or try/finally.
- One test() per scenario; use async/await.
- Structure: // Arrange / // Act / // Assert comments.
- Positive: connect, sendAndReceive, assert response fields.
- Negative: expect the connect or sendAndReceive to throw, OR assert error fields in response.
- Output ONLY valid JavaScript. No markdown fences, no explanation."""

JEST_STANDARDS_BY_TYPE: dict[APIType, str] = {
    APIType.REST: _REST_JEST_STANDARDS,
    APIType.GRAPHQL: _GRAPHQL_JEST_STANDARDS,
    APIType.SOAP: _REST_JEST_STANDARDS,       # SOAP via axios raw XML (fallback)
    APIType.GRPC: _REST_JEST_STANDARDS,       # gRPC-web via axios (fallback)
    APIType.WEBSOCKET: _WEBSOCKET_JEST_STANDARDS,
}


def validate_jest_source(source: str) -> None:
    if "test(" not in source and "it(" not in source:
        raise ValueError("Generated Jest source contains no test() or it() calls")


def jest_test_filename(ticket_id: str) -> str:
    slug = ticket_id.lower().replace("-", "_")
    return f"test_{slug}.test.js"
