"""Reusable Pytest templates and QA standards for Phase 3 script generation."""

from __future__ import annotations

from textwrap import dedent

from app.models.schemas import APIType


def build_pytest_ini() -> str:
    """Return a pytest.ini that makes a ticket's output folder runnable standalone."""
    return dedent(
        """\
        [pytest]
        markers =
            positive: Happy-path test scenarios
            negative: Error and failure test scenarios
            edge: Boundary and edge-case test scenarios
        asyncio_mode = auto
        """
    )


# ---------------------------------------------------------------------------
# conftest builders – one per API type
# ---------------------------------------------------------------------------

def build_conftest(
    ticket_id: str,
    base_url: str,
    api_key_default: str = "",
    api_type: APIType = APIType.REST,
) -> str:
    """Return a conftest.py tailored to the API protocol."""
    if api_type == APIType.GRAPHQL:
        return _build_conftest_graphql(ticket_id, base_url, api_key_default)
    if api_type == APIType.SOAP:
        return _build_conftest_soap(ticket_id, base_url)
    if api_type == APIType.GRPC:
        return _build_conftest_grpc(ticket_id, base_url)
    if api_type == APIType.WEBSOCKET:
        return _build_conftest_websocket(ticket_id, base_url)
    return _build_conftest_rest(ticket_id, base_url, api_key_default)


def _build_conftest_rest(ticket_id: str, base_url: str, api_key_default: str) -> str:
    key_literal = repr(api_key_default) if api_key_default else '""'
    return dedent(
        f'''\
        """
        Shared REST fixtures for {ticket_id} automation tests.
        Generated by QA Script Generator.
        """
        from __future__ import annotations
        import os
        import pytest
        import requests

        BASE_URL = os.getenv("API_BASE_URL", {base_url!r})
        DEFAULT_TIMEOUT = int(os.getenv("API_TIMEOUT", "30"))


        @pytest.fixture(scope="session")
        def api_key() -> str:
            return os.getenv("API_KEY", {key_literal}).strip()


        @pytest.fixture(scope="session")
        def api_client(api_key: str) -> requests.Session:
            session = requests.Session()
            session.headers.update({{"Content-Type": "application/json", "Accept": "application/json"}})
            if api_key:
                # Cover common mock API auth styles (Bearer + x-api-key, e.g. ReqRes)
                session.headers.update({{
                    "Authorization": f"Bearer {{api_key}}",
                    "x-api-key": api_key,
                }})
            return session


        @pytest.fixture(scope="session")
        def base_url() -> str:
            return BASE_URL.rstrip("/")
        '''
    )


def _build_conftest_graphql(ticket_id: str, graphql_endpoint: str, api_key_default: str) -> str:
    key_literal = repr(api_key_default) if api_key_default else '""'
    return dedent(
        f'''\
        """
        Shared GraphQL fixtures for {ticket_id} automation tests.
        Generated by QA Script Generator.
        """
        from __future__ import annotations
        import os
        from typing import Any, Dict, Optional
        import pytest
        import requests

        GRAPHQL_URL = os.getenv("GRAPHQL_URL", {graphql_endpoint!r})
        DEFAULT_TIMEOUT = int(os.getenv("API_TIMEOUT", "30"))


        @pytest.fixture(scope="session")
        def gql_client() -> requests.Session:
            session = requests.Session()
            session.headers.update({{"Content-Type": "application/json"}})
            api_key = os.getenv("API_KEY", {key_literal})
            if api_key:
                session.headers.update({{"Authorization": f"Bearer {{api_key}}"}})
            return session


        @pytest.fixture(scope="session")
        def graphql_url() -> str:
            return GRAPHQL_URL


        def gql(
            client: requests.Session,
            url: str,
            query: str,
            variables: Optional[Dict[str, Any]] = None,
        ) -> requests.Response:
            """Execute a GraphQL operation and return the raw Response."""
            payload: Dict[str, Any] = {{"query": query}}
            if variables:
                payload["variables"] = variables
            return client.post(url, json=payload, timeout=DEFAULT_TIMEOUT)
        '''
    )


def _build_conftest_soap(ticket_id: str, wsdl_url: str) -> str:
    return dedent(
        f'''\
        """
        Shared SOAP fixtures for {ticket_id} automation tests.
        Generated by QA Script Generator.

        Requires: pip install zeep
        """
        from __future__ import annotations
        import os
        import pytest

        WSDL_URL = os.getenv("WSDL_URL", {wsdl_url!r})


        @pytest.fixture(scope="session")
        def soap_client():
            """Return a zeep SOAP client configured with the WSDL URL."""
            try:
                import zeep  # noqa: WPS433
            except ImportError as exc:
                raise ImportError("Install zeep: pip install zeep") from exc
            return zeep.Client(WSDL_URL)


        @pytest.fixture(scope="session")
        def wsdl_url() -> str:
            return WSDL_URL
        '''
    )


def _build_conftest_grpc(ticket_id: str, server_address: str) -> str:
    # Strip http(s):// prefix for gRPC addresses
    addr = server_address.replace("https://", "").replace("http://", "").rstrip("/")
    if ":" not in addr:
        addr = f"{addr}:50051"
    return dedent(
        f'''\
        """
        Shared gRPC fixtures for {ticket_id} automation tests.
        Generated by QA Script Generator.

        Requires: pip install grpcio grpcio-tools
        NOTE: Generate Python stubs from your .proto file before running:
              python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. <your_service>.proto
        """
        from __future__ import annotations
        import os
        import pytest

        GRPC_SERVER = os.getenv("GRPC_SERVER", {addr!r})


        @pytest.fixture(scope="session")
        def grpc_channel():
            """Return an insecure gRPC channel to the server."""
            try:
                import grpc  # noqa: WPS433
            except ImportError as exc:
                raise ImportError("Install grpcio: pip install grpcio") from exc
            channel = grpc.insecure_channel(GRPC_SERVER)
            yield channel
            channel.close()


        @pytest.fixture(scope="session")
        def grpc_server() -> str:
            return GRPC_SERVER
        '''
    )


def _build_conftest_websocket(ticket_id: str, ws_url: str) -> str:
    # Normalise to ws:// if http:// was passed
    ws = ws_url.replace("https://", "wss://").replace("http://", "ws://")
    return dedent(
        f'''\
        """
        Shared WebSocket fixtures for {ticket_id} automation tests.
        Generated by QA Script Generator.

        Requires: pip install websockets pytest-asyncio
        """
        from __future__ import annotations
        import json
        import os
        import pytest

        WS_URL = os.getenv("WS_URL", {ws!r})


        @pytest.fixture(scope="session")
        def ws_url() -> str:
            return WS_URL


        async def ws_send_recv(ws_url: str, payload: dict, timeout: float = 5.0) -> dict:
            """Connect, send one JSON message, receive one JSON reply, then close."""
            try:
                import websockets  # noqa: WPS433
            except ImportError as exc:
                raise ImportError("Install websockets: pip install websockets") from exc
            async with websockets.connect(ws_url, open_timeout=timeout) as ws:
                await ws.send(json.dumps(payload))
                raw = await asyncio.wait_for(ws.recv(), timeout=timeout)
                return json.loads(raw)
        '''
    )


# ---------------------------------------------------------------------------
# QA standards prompts – one per API type
# ---------------------------------------------------------------------------

_REST_STANDARDS = """Internal QA automation standards for REST APIs (MUST follow exactly):
- Use pytest with the `api_client`, `api_key`, and `base_url` fixtures from conftest.py.
- One test function per scenario; name functions `test_<snake_case_scenario_name>`.
- Apply pytest markers: @pytest.mark.positive, @pytest.mark.negative, or @pytest.mark.edge.
- Each test docstring must include the ticket id and scenario description.
- Structure each test with # Arrange / # Act / # Assert comments.
- Use `requests` via the `api_client` fixture; build full URLs with f"{base_url}{endpoint}".
- Assert HTTP status codes and key response fields where applicable.
- Do NOT redefine fixtures; do NOT include conftest content in the test module.
- Import only: pytest, typing if needed. No unused imports.
- Output ONLY valid Python source code for a single test module. No markdown fences or explanation."""

_GRAPHQL_STANDARDS = """Internal QA automation standards for GraphQL APIs (MUST follow exactly):
- Use pytest with the `gql_client`, `graphql_url` fixtures and the `gql()` helper from conftest.py.
- Import `gql` from conftest: `from conftest import gql`
- One test function per scenario; name functions `test_<snake_case_scenario_name>`.
- Apply pytest markers: @pytest.mark.positive, @pytest.mark.negative, or @pytest.mark.edge.
- Each test docstring must include the ticket id and scenario description.
- Structure each test with # Arrange / # Act / # Assert comments.
- GraphQL always returns HTTP 200; check `response.json()["data"]` for success and `response.json().get("errors")` for errors.
- Positive tests: assert "errors" not in response.json() and assert data fields are present.
- Negative tests: assert response.json().get("errors") is not None.
- Write queries/mutations as inline triple-quoted strings.
- Do NOT redefine fixtures; do NOT include conftest content in the test module.
- Import only: pytest, typing if needed. No unused imports.
- Output ONLY valid Python source code for a single test module. No markdown fences or explanation."""

_SOAP_STANDARDS = """Internal QA automation standards for SOAP APIs (MUST follow exactly):
- Use pytest with the `soap_client` and `wsdl_url` fixtures from conftest.py.
- One test function per scenario; name functions `test_<snake_case_scenario_name>`.
- Apply pytest markers: @pytest.mark.positive, @pytest.mark.negative, or @pytest.mark.edge.
- Each test docstring must include the ticket id and scenario description.
- Structure each test with # Arrange / # Act / # Assert comments.
- Call SOAP operations via `soap_client.service.<OperationName>(field=value, ...)`.
- Positive tests: assert result is not None and check key response fields.
- Negative tests: use pytest.raises(zeep.exceptions.Fault) to catch SOAP faults.
- Import zeep.exceptions for fault handling.
- Do NOT redefine fixtures; do NOT include conftest content in the test module.
- Import only: pytest, zeep.exceptions if needed. No unused imports.
- Output ONLY valid Python source code for a single test module. No markdown fences or explanation."""

_GRPC_STANDARDS = """Internal QA automation standards for gRPC APIs (MUST follow exactly):
- Use pytest with the `grpc_channel` fixture from conftest.py.
- Import the generated stub classes (assumed to be importable from the project root).
- One test function per scenario; name functions `test_<snake_case_scenario_name>`.
- Apply pytest markers: @pytest.mark.positive, @pytest.mark.negative, or @pytest.mark.edge.
- Each test docstring must include the ticket id and scenario description.
- Structure each test with # Arrange / # Act / # Assert comments.
- Create stubs inside the test: `stub = <ServiceName>Stub(grpc_channel)`.
- Use `grpc.StatusCode` for asserting error codes on negative tests (wrap in try/except grpc.RpcError).
- Positive tests: assert response fields match expected values.
- Negative tests: catch grpc.RpcError and assert e.code() == grpc.StatusCode.<CODE>.
- For streaming RPCs, iterate over the response and collect items before asserting.
- Import: pytest, grpc, and your generated _pb2 / _pb2_grpc modules.
- Do NOT redefine fixtures; do NOT include conftest content in the test module.
- Output ONLY valid Python source code for a single test module. No markdown fences or explanation."""

_WEBSOCKET_STANDARDS = """Internal QA automation standards for WebSocket APIs (MUST follow exactly):
- Use pytest-asyncio; mark ALL test functions with @pytest.mark.asyncio.
- Use the `ws_url` fixture and `ws_send_recv()` helper from conftest.py.
- Import: `from conftest import ws_send_recv`
- One test function per scenario; name functions `test_<snake_case_scenario_name>`.
- Apply BOTH pytest markers: @pytest.mark.asyncio AND @pytest.mark.positive/negative/edge.
- Each test docstring must include the ticket id and scenario description.
- Structure each test with # Arrange / # Act / # Assert comments.
- For connection tests: use `async with websockets.connect(ws_url) as ws:`.
- For negative tests: assert error fields in the response OR use pytest.raises(websockets.exceptions.WebSocketException).
- For subscribe/receive tests: use async for or asyncio.wait_for() to await messages.
- Import: pytest, asyncio, websockets, json as needed.
- Do NOT redefine fixtures; do NOT include conftest content in the test module.
- Output ONLY valid Python source code for a single test module. No markdown fences or explanation."""

QA_STANDARDS_BY_TYPE: dict[APIType, str] = {
    APIType.REST: _REST_STANDARDS,
    APIType.GRAPHQL: _GRAPHQL_STANDARDS,
    APIType.SOAP: _SOAP_STANDARDS,
    APIType.GRPC: _GRPC_STANDARDS,
    APIType.WEBSOCKET: _WEBSOCKET_STANDARDS,
}

# Keep backward-compat alias
QA_STANDARDS_PROMPT = _REST_STANDARDS
